version: '3.3'
services:
  api:
    image: tx-web-backend:latest
    build:
      context: .
    ports:
      - "8080:8080"
  ui:
    image: tx-web-frontend:latest
    build:
      context: ./ui
    command: npm start
    depends_on:
      - api
    ports:
      - "3000:3000"